variables:
  buildConfiguration: 'Release'
jobs:
- job: Angular
  steps:
  
  - script: |
      cd src/angular7
      echo '###########################################################'
      echo '#          Installing angular cli                         #'
      echo '###########################################################'
      
      sudo rm package-lock.json
      #sudo npm rm -rf node_modules
      sudo npm install --save-dev @angular/cli@latest
      
      
      
      
      
      #sudo ng update 
       
    displayName: 'Installing angular cli'

  - script: |
      cd src/angular7
      sudo npm uninstall @angular-devkit/build-angular
      sudo npm i --save-dev @angular-devkit/build-angular@latest
    displayName: 'Removing and installing angular-devkit'

  - script: |
      cd src/angular7
      sudo npm install -g rxjs-tslint 
    displayName: 'Installing rxjs-tslint'

  - script: |
      cd src/angular7
      sudo npm install --save-dev typescript@3.4.5
    displayName: 'Installing typescript'

  - script: 
      cd src/angular7
      sudo npm link @angular/cli
    displayName: 'Linking angular cli'

  - script: |
      cd src/angular7
      sudo npm install @angular-devkit/schematics @angular-devkit/core @schematics/angular
    displayName: 'Installing angular-devkit/schematics'

  - script: |
       cd src/angular7
       ng update @angular/cli @angular/core --allow-dirty
    displayName: 'Updating angular/cli'

  - task: DeleteFiles@1
    displayName: 'Delete JUnit files'
    inputs:
      SourceFolder: src/angular7/junit
      Contents: 'TEST*.xml'
  
 # - task: Npm@1
  #  displayName: 'npm install'
  #  inputs:
  #    command: install
  #    workingDir: src/angular7

  - task: Npm@1
    displayName: 'Build Angular'
    inputs:
      command: custom
      customCommand: run build -- --prod
      workingDir: src/angular7
  
  - task: PublishPipelineArtifact@0
    inputs:
      artifactName: 'angular'
      targetPath: 'src/angular7/dist'
  
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: 'src/angular7/dist'
      ArtifactName: angular2

  #- task: Npm@1
   # displayName: 'Test Angular'
    #inputs:
     # command: custom
      #customCommand: run test -- --watch=false --code-coverage
      #workingDir: src/angular7
  
  - script: |
      cd src/angular7
      sudo npm install --save-dev @types/node@latest
      npm run test -- --watch=false --code-coverage
    displayName: 'Executing unit tests'
    
 # - task: PublishCodeCoverageResults@1
  #  displayName: 'Publish code coverage Angular results'
  #  condition: succeededOrFailed()
  #  inputs:
   #   codeCoverageTool: Cobertura
    #  summaryFileLocation: 'src/angular7/coverage/cobertura-coverage.xml'
    #  reportDirectory: src/angular7/coverage
    #  failIfCoverageEmpty: true
  
  #- task: PublishTestResults@2
  #  displayName: 'Publish Angular test results'
  #  condition: succeededOrFailed()
   # inputs:
   #   searchFolder: $(System.DefaultWorkingDirectory)/src/angular7/junit
   #   testRunTitle: Angular
   #   testResultsFormat: JUnit
    #  testResultsFiles: "**/TESTS*.xml"
  
  - task: Npm@1
    displayName: 'Lint Angular'
    inputs:
      command: custom
      customCommand: run lint --  --format=stylish
      workingDir: src/angular7
      
  - script: |
     
      cd src/angular7

      #sudo npm install -g webdriver-manager@12.1.4 --force
      #sudo npm install -g protractor --force
      #sudo node node_modules/.bin/webdriver-manager version
      #sudo node node_modules/.bin/webdriver-manager update --force
      #node node_modules/.bin/webdriver-manager update --versions.chrome=74.0.3729.6 --gecko false --standalone false
      #sudo npm i postinstall --force

      #npm i
      #npm i postinstall
      
      #node node_modules/.bin/webdriver-manager update --versions.chrome=77.0.3865.75
    displayName: 'Updating webdriver'        
    
    #- task: Npm@1
   # displayName: 'E2E Test Angular'
    #inputs:
     # command: custom
     # customCommand: ng e2e
     # workingDir: src/angular7

  - script: |
      cd src/angular7  
      sudo npm link @angular/cli
      
      #sudo ng update @angular/cli
      #echo '##########################Installing protractor builder############################################'
      #sudo npm install @angular-devkit/build-angular:protractor
      
      #sudo npm uninstall @angular-devkit/build-angular
      echo '###################################################################################################'
      echo '#                                  Starting E2E Tests                                             #'
      echo '###################################################################################################'
      ng e2e
    displayName: 'Running E2E Tests'

  
  - task: PublishTestResults@2
    displayName: 'Publish Angular E2E test results'
    condition: succeededOrFailed()
    inputs:
      searchFolder: $(System.DefaultWorkingDirectory)/src/angular7/e2e/junit
      testRunTitle: Angular_E2E
      testResultsFormat: JUnit
      testResultsFiles: "**/junit*.xml"